// Comprehensive Emoji Search Dictionary & Fuzzy Search Engine

export interface EmojiData {
  emoji: string;
  name: string;
  keywords: string[];
}

export const EMOJI_DATABASE: Record<string, string[]> = {
  // Smileys & Emotions
  "😀": ["grinning", "face", "smile", "happy", "joy", "cheerful"],
  "😃": ["smiley", "smile", "happy", "face", "joy", "haha", "cheerful"],
  "😄": ["smile", "happy", "joy", "laugh", "cheerful", "pleased"],
  "😁": ["beam", "grin", "teeth", "happy", "smile", "laugh"],
  "😆": ["laughing", "satisfied", "haha", "lol", "happy", "funny", "giggle"],
  "😅": ["sweat_smile", "hot", "nervous", "relief", "happy", "laugh"],
  "😂": ["joy", "tears", "laugh", "cry", "lol", "haha", "funny", "rofl", "hilarious"],
  "🤣": ["rofl", "rolling", "laughing", "floor", "lol", "haha", "funny"],
  "🥲": ["smiling_face_with_tear", "grateful", "touched", "sad_happy", "tear", "smile"],
  "☺️": ["smiling", "warm", "peaceful", "calm", "blush", "pleasant"],
  "😊": ["blush", "smile", "happy", "pleased", "warm", "content"],
  "😇": ["halo", "innocent", "angel", "heaven", "good", "pure"],
  "🙂": ["slightly_smiling", "okay", "fine", "smile"],
  "🙃": ["upside_down", "silly", "sarcastic", "irony", "playful"],
  "😉": ["wink", "flirt", "playful", "joke", "secret"],
  "😌": ["relieved", "relaxed", "peace", "calm", "serene"],
  "😍": ["heart_eyes", "love", "crush", "adore", "heart", "beautiful", "romance"],
  "🥰": ["smiling_face_with_three_hearts", "love", "blessed", "affection", "adore", "crush", "sweet"],
  "😘": ["kissing_heart", "kiss", "love", "flirt", "romantic", "affection"],
  "😗": ["kissing", "whistle", "kiss", "pucker"],
  "😙": ["kissing_smiling_eyes", "kiss", "sweet"],
  "😚": ["kissing_closed_eyes", "kiss", "affection", "love"],
  "😋": ["yum", "tasty", "delicious", "tongue", "food", "yummy"],
  "😛": ["stuck_out_tongue", "playful", "silly", "kidding"],
  "😝": ["stuck_out_tongue_closed_eyes", "taste", "prank", "silly", "fun"],
  "😜": ["stuck_out_tongue_winking_eye", "winking", "crazy", "party", "joke"],
  "🤪": ["zany", "crazy", "goofy", "wild", "party"],
  "🤨": ["raised_eyebrow", "suspicious", "skeptical", "doubt", "disbelief"],
  "🧐": ["monocle", "curious", "inspect", "smart", "analyze", "detective"],
  "🤓": ["nerd", "geek", "glasses", "smart", "studious"],
  "😎": ["sunglasses", "cool", "boss", "chill", "awesome", "summer"],
  "🥸": ["disguise", "mustache", "glasses", "incognito", "secret"],
  "🤩": ["star_struck", "excited", "wow", "stars", "celebrity", "amazing"],
  "🥳": ["partying", "celebrate", "party", "birthday", "hat", "congrats", "cheers"],
  "😏": ["smirk", "smug", "flirt", "suggestive", "mischievous"],
  "😒": ["unamused", "meh", "bored", "annoyed", "side_eye", "displeased"],
  "😞": ["disappointed", "sad", "depressed", "down", "unhappy"],
  "😔": ["pensive", "sad", "regret", "depressed", "sorrow"],
  "😟": ["worried", "nervous", "anxious", "concern"],
  "😕": ["confused", "puzzled", "uncertain", "doubt"],
  "🙁": ["slightly_frowning", "sad", "displeased"],
  "☹️": ["frowning", "sad", "unhappy", "sorrow"],
  "😣": ["persevering", "struggling", "frustrated", "pain"],
  "😖": ["confounded", "frustrated", "quiver", "distressed"],
  "😫": ["tired", "exhausted", "screaming", "fed_up"],
  "😩": ["weary", "frustrated", "tired", "sad", "crying"],
  "🥺": ["pleading", "begging", "puppy_eyes", "cute", "please", "mercy"],
  "😢": ["crying", "tear", "sad", "sorrow", "upset", "hurt"],
  "😭": ["sob", "crying", "tears", "sad", "bawling", "stream", "grief"],
  "😤": ["triumph", "steaming", "angry", "proud", "frustrated", "huff"],
  "😠": ["angry", "mad", "annoyed", "grumpy"],
  "😡": ["rage", "pouting", "furious", "mad", "angry", "red"],
  "🤬": ["cursing", "swearing", "censored", "furious", "angry", "profanity"],
  "🤯": ["exploding_head", "mind_blown", "shock", "omg", "wow", "unbelievable"],
  "😳": ["flushed", "blushing", "shocked", "embarrassed", "shy", "surprised"],
  "🥵": ["hot", "sweating", "heat", "summer", "spicy"],
  "🥶": ["cold", "freezing", "ice", "frost", "winter", "shiver"],
  "😱": ["scream", "shock", "scared", "fear", "horror", "munch", "omg"],
  "😨": ["fearful", "scared", "shocked", "nervous"],
  "😰": ["cold_sweat", "nervous", "anxious", "scared"],
  "😥": ["sad_relieved", "phew", "sweat", "disappointed"],
  "😓": ["downcast_sweat", "tired", "stressed", "work"],
  "🤗": ["hugs", "hug", "embrace", "friendly", "open", "warm"],
  "🤔": ["thinking", "hmm", "ponder", "wonder", "curious", "idea"],
  "🤭": ["hand_over_mouth", "giggle", "oops", "secret", "teehee"],
  "🤫": ["shushing", "quiet", "silence", "shh", "secret"],
  "🤥": ["lying", "pinocchio", "long_nose", "fake", "liar"],
  "😶": ["no_mouth", "silent", "speechless", "quiet"],
  "😐": ["neutral", "meh", "straight_face", "unimpressed"],
  "😑": ["expressionless", "blank", "unfazed", "bored"],
  "😬": ["grimacing", "awkward", "teeth", "nervous", "cringe"],
  "🙄": ["rolling_eyes", "eyeroll", "whatever", "annoyed", "frustrated"],
  "😯": ["hushed", "surprised", "whoa", "curious"],
  "😦": ["frowning_open_mouth", "gasp", "surprised", "scared"],
  "😧": ["anguished", "shocked", "scared", "nervous"],
  "😮": ["open_mouth", "surprised", "wow", "gasp", "shock"],
  "😲": ["astonished", "shocked", "amazed", "speechless"],
  "🥱": ["yawning", "tired", "sleepy", "bored"],
  "😴": ["sleeping", "zzz", "tired", "bed", "rest", "night"],
  "🤤": ["drooling", "delicious", "craving", "yummy", "sleep"],
  "😪": ["sleepy", "tired", "bubble", "rest"],
  "😵": ["dizzy", "knocked_out", "dead", "unconscious", "drunk"],
  "🤐": ["zipper_mouth", "secret", "sealed", "silent", "quiet"],
  "🥴": ["woozy", "drunk", "tipsy", "dazed", "hangover"],
  "🤢": ["nauseated", "sick", "gross", "vomit", "disgusted", "green"],
  "🤮": ["vomiting", "barf", "puke", "gross", "sick"],
  "🤧": ["sneezing", "sick", "tissue", "allergy", "cold"],
  "😷": ["mask", "sick", "doctor", "health", "covid", "ill"],
  "🤒": ["thermometer", "fever", "temperature", "sick"],
  "🤕": ["bandage", "hurt", "injured", "headache", "wound"],
  "🤑": ["money_mouth", "rich", "cash", "dollar", "wealth"],
  "🤠": ["cowboy", "hat", "western", "yeehaw"],
  "😈": ["smiling_imp", "devil", "evil", "naughty", "horns", "purple"],
  "👿": ["imp", "angry_devil", "furious", "demon"],
  "👹": ["ogre", "monster", "japanese", "demon"],
  "👺": ["goblin", "red_mask", "tengu"],
  "🤡": ["clown", "circus", "fool", "joke"],
  "💩": ["poop", "poo", "crap", "shit", "funny", "toilet"],
  "👻": ["ghost", "spooky", "halloween", "haunt", "boo"],
  "💀": ["skull", "dead", "death", "skeleton", "dying_of_laughter", "rip"],
  "☠️": ["skull_crossbones", "danger", "poison", "pirate", "dead"],
  "👽": ["alien", "ufo", "space", "extraterrestrial"],
  "👾": ["space_invader", "game", "retro", "pixel", "arcade"],
  "🤖": ["robot", "bot", "ai", "machine", "tech"],
  "🎃": ["jack_o_lantern", "pumpkin", "halloween", "fall"],

  // Hands & Body
  "👋": ["wave", "hello", "hi", "bye", "goodbye", "hand"],
  "🤚": ["raised_back_of_hand", "stop", "halt"],
  "🖐": ["raised_hand_fingers_splayed", "five", "high_five"],
  "✋": ["raised_hand", "stop", "high_five", "halt"],
  "🖖": ["vulcan_salute", "spock", "star_trek", "peace"],
  "👌": ["ok_hand", "perfect", "okay", "fine", "good"],
  "🤌": ["pinched_fingers", "italian", "chef_kiss", "what"],
  "🤏": ["pinching_hand", "small", "tiny", "little_bit"],
  "✌️": ["peace", "victory", "two", "v_sign"],
  "🤞": ["crossed_fingers", "luck", "hopeful", "wish"],
  "🤟": ["love_you_gesture", "ily", "sign_language"],
  "🤘": ["sign_of_the_horns", "rock", "metal", "party"],
  "🤙": ["call_me_hand", "shaka", "hang_loose", "surf"],
  "👈": ["point_left", "direction", "finger"],
  "👉": ["point_right", "direction", "finger"],
  "👆": ["point_up", "direction", "look_above"],
  "👇": ["point_down", "direction", "below"],
  "☝️": ["index_pointing_up", "one", "first", "listen"],
  "👍": ["thumbsup", "like", "agree", "yes", "good", "approved", "ok"],
  "👎": ["thumbsdown", "dislike", "no", "bad", "disapprove"],
  "✊": ["fist", "power", "punch", "solidarity"],
  "👊": ["oncoming_fist", "punch", "brofist", "fist_bump"],
  "🤛": ["left_facing_fist", "fist_bump"],
  "🤜": ["right_facing_fist", "fist_bump"],
  "👏": ["clapping_hands", "applause", "bravo", "praise", "claps"],
  "🙌": ["raising_hands", "celebrate", "hooray", "hallelujah", "praise"],
  "🤲": ["palms_up_together", "pray", "dua", "ask"],
  "🤝": ["handshake", "deal", "agreement", "meeting", "partner"],
  "🙏": ["folded_hands", "pray", "please", "thank_you", "namaste", "gratitude", "blessing"],
  "💪": ["muscle", "flex", "strong", "bicep", "gym", "workout", "power"],
  "🧠": ["brain", "smart", "intellect", "mind", "think"],
  "👀": ["eyes", "look", "see", "watch", "peeping", "stare"],
  "👄": ["mouth", "lips", "kiss", "talk"],
  "💋": ["kiss_mark", "kiss", "lips", "romantic", "love"],

  // Hearts & Symbols
  "❤️": ["red_heart", "love", "heart", "romance", "passion", "valentine", "crush", "like"],
  "🧡": ["orange_heart", "love", "warmth", "friendship"],
  "💛": ["yellow_heart", "friendship", "happiness", "love"],
  "💚": ["green_heart", "nature", "jealousy", "love"],
  "💙": ["blue_heart", "trust", "loyalty", "love"],
  "💜": ["purple_heart", "bts", "royalty", "love"],
  "🖤": ["black_heart", "dark", "sorrow", "love"],
  "🤍": ["white_heart", "pure", "peace", "love"],
  "🤎": ["brown_heart", "chocolate", "love"],
  "💔": ["broken_heart", "heartbreak", "sad", "breakup", "hurt"],
  "❤️‍🔥": ["heart_on_fire", "passion", "love", "lust", "hot"],
  "❤️‍🩹": ["mending_heart", "healing", "recovery", "better"],
  "❣️": ["heart_exclamation", "love", "attention"],
  "💕": ["two_hearts", "love", "romance", "pink"],
  "💞": ["revolving_hearts", "love", "sweet", "crush"],
  "💓": ["beating_heart", "pulse", "love", "alive"],
  "💗": ["growing_heart", "excited", "love", "blush"],
  "💖": ["sparkling_heart", "special", "love", "shine"],
  "💘": ["cupid", "arrow", "love", "romance"],
  "💝": ["gift_heart", "ribbon", "love", "present"],
  "💟": ["heart_decoration", "purple", "sweet"],
  "🔥": ["fire", "flame", "lit", "hot", "trending", "burn"],
  "✨": ["sparkles", "magic", "clean", "special", "star", "shine", "glitter"],
  "⭐": ["star", "favorite", "yellow", "night"],
  "🌟": ["glowing_star", "shining", "success", "bright"],
  "💫": ["dizzy", "star", "swoosh", "magic"],
  "⚡": ["lightning", "zap", "electric", "power", "fast"],
  "🎉": ["party_popper", "tada", "celebrate", "congratulations", "party"],
  "🎊": ["confetti_ball", "celebrate", "festival"],
  "🎈": ["balloon", "party", "celebration", "birthday"],
  "🎁": ["gift", "present", "birthday", "christmas", "box"],
  // Animals
  "🐶": ["dog", "doggy", "puppy", "pet", "woof", "bark"],
  "🐱": ["cat", "kitty", "kitten", "pet", "meow"],
  "🐭": ["mouse", "rat", "cheese"],
  "🐹": ["hamster", "pet", "cute"],
  "🐰": ["rabbit", "bunny", "easter"],
  "🦊": ["fox", "clever", "cunning", "orange"],
  "🐻": ["bear", "teddy", "brown"],
  "🐼": ["panda", "bamboo", "cute", "china"],
  "🐨": ["koala", "australia", "eucalyptus"],
  "🐯": ["tiger", "wild", "cat", "stripes"],
  "🦁": ["lion", "king", "brave", "safari"],
  "🐮": ["cow", "beef", "milk", "moo"],
  "🐷": ["pig", "pork", "farm", "oink"],
  "🐸": ["frog", "toad", "green", "amphibian"],
  "🐵": ["monkey", "banana", "ape", "chimpanzee"],
  "🙈": ["see_no_evil", "monkey", "shy", "hide", "blind"],
  "🙉": ["hear_no_evil", "monkey", "deaf"],
  "🙊": ["speak_no_evil", "monkey", "secret", "gasp", "mute"],
  "🐔": ["chicken", "hen", "farm", "bird"],
  "🐧": ["penguin", "cold", "antarctica", "ice", "bird"],
  "🐦": ["bird", "tweet", "fly"],
  "🐤": ["baby_chick", "cute", "yellow"],
  "🦆": ["duck", "quack", "pond", "bird"],
  "🦅": ["eagle", "usa", "freedom", "bird"],
  "🦉": ["owl", "night", "wise", "bird"],
  "🦇": ["bat", "batman", "vampire", "halloween"],
  "🐺": ["wolf", "howl", "wild", "moon"],
  "🐗": ["boar", "wild_pig"],
  "🐴": ["horse", "equestrian", "ride", "farm"],
  "🦄": ["unicorn", "magic", "fantasy", "rainbow"],
  "🐝": ["bee", "honey", "honeybee", "sting", "bug"],
  "🦋": ["butterfly", "beautiful", "insect", "wings"],
  "🐌": ["snail", "slow", "shell"],
  "🐞": ["ladybug", "bug", "ladybird"],
  "🐜": ["ant", "bug", "small"],
  "🕷": ["spider", "spooky", "halloween", "web"],
  "🐢": ["turtle", "tortoise", "slow", "green"],
  "🐍": ["snake", "reptile", "slither", "poison"],
  "🐙": ["octopus", "squid", "ocean", "sea"],
  "🦀": ["crab", "cancer", "seafood", "ocean"],
  "🐠": ["tropical_fish", "aquarium", "nemo", "sea"],
  "🐟": ["fish", "seafood", "ocean"],
  "🐬": ["dolphin", "ocean", "smart", "sea"],
  "🐳": ["whale", "spouting", "ocean", "sea"],
  "🦈": ["shark", "ocean", "jaws", "danger"],
  "🐊": ["crocodile", "alligator", "reptile"],
  "🐅": ["tiger", "wild"],
  "🐘": ["elephant", "trunk", "big", "safari"],
  "🐪": ["camel", "desert", "hump"],
  "🦒": ["giraffe", "tall", "neck", "safari"],
  "🦘": ["kangaroo", "australia", "jump"],
  "🐈": ["cat", "pet", "meow"],
  "🐕": ["dog", "pet", "loyal"],
  "🕊": ["dove", "peace", "bird", "white"],
  "🌵": ["cactus", "desert", "plant", "dry"],
  "🎄": ["christmas_tree", "holiday", "xmas", "december"],
  "🌲": ["evergreen", "tree", "pine", "forest", "nature"],
  "🌳": ["deciduous_tree", "nature", "tree", "green"],
  "🌴": ["palm_tree", "beach", "tropical", "vacation", "summer"],
  "🌱": ["seedling", "sprout", "nature", "grow", "new"],
  "🌿": ["herb", "plant", "green", "leaves"],
  "☘️": ["shamrock", "ireland", "lucky", "green"],
  "🍀": ["four_leaf_clover", "luck", "lucky", "green"],
  "🍃": ["leaves", "wind", "blow", "nature"],
  "🍂": ["fallen_leaf", "autumn", "fall"],
  "🍁": ["maple_leaf", "canada", "fall", "autumn"],
  "🍄": ["mushroom", "fungus", "toadstool", "mario"],
  "🌷": ["tulip", "flower", "spring"],
  "🌺": ["hibiscus", "tropical", "flower"],
  "🌼": ["blossom", "flower", "yellow"],
  "🌞": ["sun_with_face", "warm", "sunny", "summer"],
  "🌙": ["crescent_moon", "night", "sleep", "islam"],
  "☁️": ["cloud", "weather", "overcast"],
  "🌧": ["rain", "rainy", "storm", "weather", "water"],
  "⛈": ["thunderstorm", "lightning", "storm", "rain"],
  "❄️": ["snowflake", "winter", "cold", "snow", "ice"],
  "☃️": ["snowman", "winter", "snow", "cold"],
  "💧": ["droplet", "water", "sweat", "tear"],
  "🌊": ["wave", "ocean", "sea", "tsunami", "surf"],

  // Food & Drink
  "🍏": ["green_apple", "fruit", "healthy"],
  "🍎": ["red_apple", "fruit", "apple"],
  "🍐": ["pear", "fruit"],
  "🍊": ["tangerine", "orange", "citrus", "fruit"],
  "🍋": ["lemon", "sour", "citrus", "yellow"],
  "🍌": ["banana", "fruit", "yellow", "monkey"],
  "🍉": ["watermelon", "summer", "fruit", "melon"],
  "🍇": ["grapes", "fruit", "wine", "purple"],
  "🍓": ["strawberry", "berry", "sweet", "red"],
  "🫐": ["blueberries", "berry", "fruit"],
  "🍒": ["cherries", "fruit", "sweet", "pair"],
  "🍑": ["peach", "fruit", "butt"],
  "🥭": ["mango", "tropical", "fruit", "sweet"],
  "🍍": ["pineapple", "tropical", "fruit"],
  "🥥": ["coconut", "tropical", "palm"],
  "🥝": ["kiwi", "fruit", "green"],
  "🍅": ["tomato", "red", "vegetable"],
  "🥑": ["avocado", "guacamole", "healthy"],
  "🌽": ["corn", "popcorn", "maize"],
  "🌶": ["hot_pepper", "spicy", "chili", "hot"],
  "🥔": ["potato", "french_fries", "veg"],
  "🍞": ["bread", "toast", "bakery"],
  "🥐": ["croissant", "french", "bakery"],
  "🧀": ["cheese", "cheddar", "swiss"],
  "🥚": ["egg", "breakfast", "chicken"],
  "🍳": ["cooking", "fried_egg", "breakfast"],
  "🥓": ["bacon", "meat", "breakfast", "pork"],
  "🥩": ["meat", "steak", "beef"],
  "🍗": ["poultry_leg", "chicken", "meat", "drumstick"],
  "🍖": ["meat_on_bone", "ribs", "meat"],
  "🌭": ["hotdog", "sausage", "fast_food"],
  "🍔": ["burger", "hamburger", "fast_food", "beef"],
  "🍟": ["french_fries", "fries", "mcdonalds", "chips"],
  "🍕": ["pizza", "slice", "cheese", "italian"],
  "🥪": ["sandwich", "lunch", "bread"],
  "🌮": ["taco", "mexican", "fast_food"],
  "🌯": ["burrito", "wrap", "mexican"],
  "🥗": ["salad", "healthy", "vegan", "green"],
  "🍝": ["spaghetti", "pasta", "noodles", "italian"],
  "🍜": ["ramen", "noodles", "soup", "japanese"],
  "🍲": ["stew", "soup", "pot", "hot"],
  "🍛": ["curry", "rice", "indian", "asian"],
  "🍣": ["sushi", "japanese", "fish", "rice"],
  "🍱": ["bento", "lunch_box", "japanese"],
  "🥟": ["dumpling", "momo", "chinese", "asian"],
  "🍤": ["fried_shrimp", "tempura", "seafood"],
  "🍙": ["rice_ball", "onigiri", "japanese"],
  "🍚": ["rice", "steamed_rice", "bowl"],
  "🍨": ["ice_cream", "dessert", "cold", "sweet"],
  "🍦": ["soft_ice_cream", "cone", "vanilla"],
  "🍰": ["shortcake", "cake", "sweet", "birthday", "slice"],
  "🎂": ["birthday_cake", "celebrate", "party", "candles"],
  "🍮": ["custard", "pudding", "flan"],
  "🍭": ["lollipop", "candy", "sweet"],
  "🍬": ["candy", "sweet", "sugar"],
  "🍫": ["chocolate", "candy", "sweet", "bar"],
  "🍿": ["popcorn", "movie", "cinema", "snack"],
  "🍩": ["doughnut", "donut", "sweet", "bakery"],
  "🍪": ["cookie", "biscuit", "chocolate_chip"],
  "🥛": ["milk", "glass", "drink"],
  "🫖": ["teapot", "tea", "hot_drink"],
  "☕️": ["coffee", "cafe", "espresso", "morning", "hot"],
  "🍵": ["green_tea", "tea", "matcha"],
  "🧃": ["juice_box", "drink", "kids"],
  "🥤": ["cup_with_straw", "soda", "drink"],
  "🧋": ["boba", "bubble_tea", "milk_tea"],
  "🍺": ["beer", "alcohol", "drink", "pub"],
  "🍻": ["beers", "cheers", "pub", "party", "alcohol"],
  "🥂": ["clinking_glasses", "cheers", "champagne", "celebrate", "toast"],
  "🍷": ["wine", "red_wine", "alcohol", "glass"],
  "🍸": ["cocktail", "martini", "alcohol", "bar"],
  "🍹": ["tropical_drink", "cocktail", "beach"],
  "🍾": ["champagne", "popping", "celebrate", "party"],

  // Activity & Sports
  "⚽": ["soccer", "football", "ball", "sport"],
  "🏀": ["basketball", "nba", "sport", "ball"],
  "🏈": ["american_football", "nfl", "sport"],
  "⚾": ["baseball", "mlb", "ball", "sport"],
  "🎾": ["tennis", "ball", "racket", "sport"],
  "🏐": ["volleyball", "beach", "sport"],
  "🎱": ["8ball", "pool", "billiards"],
  "🏓": ["ping_pong", "table_tennis"],
  "🏸": ["badminton", "shuttlecock"],
  "🥊": ["boxing_glove", "fight", "punch", "boxer"],
  "🥋": ["martial_arts_uniform", "karate", "judo"],
  "🛹": ["skateboard", "skater", "skate"],
  "⛷": ["skier", "ski", "snow"],
  "🏋️": ["weightlifter", "gym", "workout", "fitness", "strong"],
  "🏆": ["trophy", "winner", "first", "champion", "prize"],
  "🥇": ["first_place", "gold_medal", "champion", "winner"],
  "🥈": ["second_place", "silver_medal"],
  "🥉": ["third_place", "bronze_medal"],
  "🏅": ["sports_medal", "award", "prize"],
  "🎖": ["military_medal", "honor"],
  "🎪": ["circus_tent", "carnival", "show"],
  "🎨": ["artist_palette", "art", "paint", "draw"],
  "🎬": ["clapper_board", "movie", "film", "cinema", "action"],
  "🎤": ["microphone", "sing", "karaoke", "music"],
  "🎧": ["headphones", "music", "audio", "listen"],
  "🎼": ["musical_score", "clef", "notes"],
  "🎵": ["musical_note", "song", "tune"],
  "🎶": ["notes", "music", "songs"],
  "🎹": ["piano", "keyboard", "musical_instrument"],
  "🥁": ["drum", "beat", "music"],
  "🎷": ["saxophone", "jazz", "music"],
  "🎺": ["trumpet", "brass", "music"],
  "🎸": ["guitar", "rock", "music", "acoustic"],
  "🎻": ["violin", "classical", "music"],
  "🎮": ["video_game", "gaming", "playstation", "controller", "xbox"],
  "🕹": ["joystick", "arcade", "game"],
  "🎲": ["game_die", "dice", "gamble", "luck"],
  "🎯": ["dart", "bullseye", "target", "accuracy"],

  // Travel & Vehicles
  "🚗": ["car", "automobile", "drive", "vehicle", "red"],
  "🚕": ["taxi", "cab", "yellow"],
  "🏎": ["racing_car", "f1", "speed", "fast"],
  "🚓": ["police_car", "cops", "emergency"],
  "🚑": ["ambulance", "hospital", "emergency"],
  "🚒": ["fire_engine", "firefighter", "emergency"],
  "🚌": ["bus", "school_bus", "transit"],
  "🚚": ["truck", "delivery", "cargo"],
  "🏍": ["motorcycle", "bike", "speed"],
  "🛵": ["scooter", "vespa"],
  "🚲": ["bicycle", "bike", "cycle"],
  "✈️": ["airplane", "flight", "travel", "fly", "trip"],
  "🚀": ["rocket", "space", "launch", "moon", "crypto", "fast"],
  "🛸": ["flying_saucer", "ufo", "alien"],
  "🚁": ["helicopter", "fly", "chopper"],
  "⛵": ["sailboat", "boat", "sea"],
  "🚢": ["ship", "cruise", "boat", "ocean"],
  "🏠": ["house", "home", "building"],
  "🏡": ["house_with_garden", "home"],
  "🏢": ["office_building", "work", "city"],
  "🏥": ["hospital", "doctor", "medicine"],
  "🏦": ["bank", "money"],
  "🏨": ["hotel", "vacation", "trip"],
  "🏰": ["castle", "fairy_tale", "disney"],
  "🗽": ["statue_of_liberty", "new_york", "usa"],
  "🗼": ["tokyo_tower", "japan", "eiffel"],
  "🏖": ["beach_umbrella", "vacation", "sea", "sand"],
  "🏔": ["mountain", "snow", "everest"],
  "🌋": ["volcano", "lava", "eruption"],
  "🏕": ["camping", "tent", "nature"],

  // Objects & Tech
  "📱": ["mobile_phone", "iphone", "android", "cell"],
  "💻": ["laptop", "computer", "pc", "macbook", "tech"],
  "🖥": ["desktop_computer", "monitor", "screen"],
  "⌨️": ["keyboard", "typing", "tech"],
  "📷": ["camera", "photo", "picture", "snapshot"],
  "📸": ["camera_flash", "photo", "selfie"],
  "📹": ["video_camera", "recording", "movie"],
  "🎥": ["movie_camera", "cinema", "film"],
  "📞": ["telephone", "call", "phone"],
  "📺": ["tv", "television", "screen"],
  "📻": ["radio", "music", "broadcast"],
  "⏰": ["alarm_clock", "morning", "time", "wake_up"],
  "💡": ["light_bulb", "idea", "smart", "bright", "electricity"],
  "🔦": ["flashlight", "torch", "dark"],
  "💰": ["moneybag", "cash", "dollar", "rich", "wealth"],
  "💵": ["dollar", "cash", "money", "bill"],
  "💳": ["credit_card", "pay", "money", "visa"],
  "💎": ["gem", "diamond", "jewelry", "precious", "rich"],
  "💍": ["ring", "diamond", "marriage", "wedding", "proposal"],
  "👑": ["crown", "king", "queen", "royal"],
  "🔑": ["key", "lock", "password", "access"],
  "🔒": ["lock", "locked", "secure", "private"],
  "🔓": ["unlock", "open", "insecure"],
};

/**
 * Real, intelligent emoji search supporting english keywords, emotion names,
 * categories, and fuzzy matching.
 */
export function searchEmojis(query: string, allEmojis: string[]): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return allEmojis;

  // 1. Direct emoji character match
  if (allEmojis.includes(q)) {
    return [q, ...allEmojis.filter((e) => e !== q)];
  }

  // 2. Keyword & name matching
  const matchedWithScore: { emoji: string; score: number }[] = [];

  for (const emoji of allEmojis) {
    const keywords = EMOJI_DATABASE[emoji] || [];
    let bestScore = 0;

    for (const kw of keywords) {
      if (kw === q) {
        bestScore = Math.max(bestScore, 100); // Exact match
      } else if (kw.startsWith(q)) {
        bestScore = Math.max(bestScore, 80); // Prefix match
      } else if (kw.includes(q)) {
        bestScore = Math.max(bestScore, 50); // Substring match
      }
    }

    if (bestScore > 0) {
      matchedWithScore.push({ emoji, score: bestScore });
    }
  }

  // Sort by score descending
  matchedWithScore.sort((a, b) => b.score - a.score);
  return matchedWithScore.map((m) => m.emoji);
}
